### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by sahvinay** [JustinBusschau/hmrc-gift-aid#2]
I am from python domain and I have no background in PHP.
I have install PHP and composer installed in my centos [Linux].
Can you please guide me how I can run the test file which is present in hmrc-gift-aid/tests/GovTalk/GiftAid directory and just wanted to cross check with the data given in the mock.
I tried to run 'TestCase.php' file but it say 
`PHP Warning:  include_once(/vendor/autoload.php): failed to open stream: No such file or directory in /hmrc/index2.php on line 3`
`PHP Warning:  include_once(): Failed opening '/vendor/autoload.php' for inclusion (include_path='.:/usr/pear:/usr/php') in /hmrc/TestCase.php on line 3`
`PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /hmrc/GovTalk/GiftAid/TestCase.php on line 24`
I just want to run this test data so that I will get some ideas.
If possible add checklist for the things which need to run this test file.

My vendor path is : /hmrc/vendor
Your Test data path is : /hmrc/GovTalk/GiftAid/TestCase.php

**Comment by JustinBusschau** [comment]
Here is the full path to enlightenment:
```bash
$ git clone https://github.com/JustinBusschau/hmrc-gift-aid.git
$ cd hmrc-gift-aid
$ composer install
$ phpunit
```

That should clone the repo, install all dependencies and finally run all the tests. The full output, for me, looks like this:
```bash
justinbusschau@local:~/Dev$ git clone github:JustinBusschau/hmrc-gift-aid
Cloning into 'hmrc-gift-aid'...
remote: Counting objects: 116, done.
remote: Total 116 (delta 0), reused 0 (delta 0), pack-reused 116
Receiving objects: 100% (116/116), 50.94 KiB | 644.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
justinbusschau@local:~/Dev$ cd hmrc-gift-aid/
justinbusschau@local:~/Dev/hmrc-gift-aid$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Installing symfony/event-dispatcher (v2.8.42): Loading from cache
  - Installing guzzle/guzzle (v3.9.3): Downloading (100%)         
  - Installing justinbusschau/php-govtalk (0.2.1): Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2): Downloading (100%)         
  - Installing mockery/mockery (0.9.9): Downloading (100%)         
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Installing symfony/yaml (v2.8.42): Downloading (100%)         
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (1.2.3): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.2.2): Loading from cache
  - Installing phpunit/php-code-coverage (1.2.18): Loading from cache
  - Installing phpunit/phpunit (3.7.38): Loading from cache
  - Installing squizlabs/php_codesniffer (1.5.6): Loading from cache
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
justinbusschau@local:~/Dev/hmrc-gift-aid$ phpunit
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from ~/Dev/hmrc-gift-aid/phpunit.xml.dist

...............................

Time: 50 ms, Memory: 6.00MB

OK (31 tests, 85 assertions)
justinbusschau@local:~/Dev/hmrc-gift-aid$ 

```


The `TestCase.php` file needs to run in the correct context, which is defined in the `phpunit.xml.dist` file. You can copy that file to `phpunit.xml` locally and modify it to create your own tests, to run tests in isolation and pretty much do whatever you need... but you can learn about that elsewhere, I think that would be outside of the scope of this issue.
